version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./.env

  frontend:
    build:
      context: ./frontend
      args:
        RECAPTCHA_SITE_KEY: ${RECAPTCHA_SITE_KEY}
    env_file:
      - ./.env
    command: npm run build # Assuming a build script exists in package.json

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro # Assuming frontend build output goes to frontend/dist
    depends_on:
      - frontend
      - backend
